# Test repository configuration file.
excludes:
  paths:
  - pattern: "analyzer/src/funTest/assets/projects/synthetic/gradle/lib-without-repo/build.gradle"
    reason: "OPTIONAL_COMPONENT_OF"
    comment: "Project not delivered."
  scopes:
  - name: "testAnnotationProcessor"
    reason: "TEST_DEPENDENCY_OF"
    comment: "Test dependencies."
  - name: "testCompile"
    reason: "TEST_DEPENDENCY_OF"
    comment: "Test dependencies."
  - name: "testCompileClasspath"
    reason: "TEST_DEPENDENCY_OF"
    comment: "Test dependencies."
  - name: "testCompileOnly"
    reason: "TEST_DEPENDENCY_OF"
    comment: "Test dependencies."
  - name: "testRuntime"
    reason: "TEST_DEPENDENCY_OF"
    comment: "Test dependencies."
  - name: "testRuntimeClasspath"
    reason: "TEST_DEPENDENCY_OF"
    comment: "Test dependencies."
